apiVersion: "v1"
kind: "List"
items:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      labels:
        provider: "fabric8"
        component: "grafana"
      name: "grafana"
    spec:
      ports:
        -
          port: 80
          targetPort: "http"
      selector:
        provider: "fabric8"
        component: "grafana"
  -
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      labels:
        provider: "fabric8"
        component: "grafana"
      name: "grafana"
    spec:
      replicas: 1
      selector:
        provider: "fabric8"
        component: "grafana"
      template:
        metadata:
          labels:
            provider: "fabric8"
            component: "grafana"
        spec:
          containers:
            -
              env:
                -
                  name: "INFLUXDB_SERVICE_NAME"
                  value: "INFLUXDB_MONITORING"
                -
                  name: "GRAFANA_DEFAULT_DASHBOARD"
                  value: "/dashboard/file/kubernetes.json"
              image: "fabric8/grafana:1.9.1_2"
              name: "grafana"
              ports:
                -
                  containerPort: 3000
                  name: "http"