apiVersion: "v1"
kind: "List"
items:
  -
    apiVersion: "v1"
    kind: "ReplicationController"
    metadata:
      labels:
        provider: "fabric8"
        component: "heapster"
      name: "heapster"
    spec:
      replicas: 1
      selector:
        provider: "fabric8"
        component: "heapster"
      template:
        metadata:
          labels:
            provider: "fabric8"
            component: "heapster"
        spec:
          containers:
            -
              args:
                - "-source=kubernetes:https://kubernetes.default.svc.cluster.local?auth=&insecure=true&useServiceAccount=true"
                - "-sink=influxdb:http://influxdb-monitoring.default.svc.cluster.local:8086"
              image: "kubernetes/heapster:V0.14.2"
              name: "heapster"
          serviceAccount: "heapster"