---
- name: Disable all repositories
  command: subscription-manager repos --disable="*"

- name: Enable RHEL repositories
  command: subscription-manager repos \
               --enable="rhel-7-server-rpms" \
               --enable="rhel-7-server-extras-rpms" \
               --enable="rhel-7-server-ose-3.0-rpms"
